Add missing headers for C++23
Add headers to resolve C++23 build errors because C++23 removed
transitive includes so you have to add the headers directly.

Errors:
system/chre/host/hal_generic/common/hal_client_manager.cc:612:10: error:
no member named 'sort' in namespace 'std'
  612 |     std::sort(endpointIds.begin(), endpointIds.end());

Flag: EXEMPT BUGFIX
Bug: 429048222
Test: m chre_hal_unit_tests
Change-Id: I1ad7ee5daf893d01c9e530add2f10eadc12eac62